# Generated by Django 6.0.4 on 2026-04-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='armazenamento',
            field=models.CharField(default='Não informado', max_length=100),
        ),
    ]
