# Generated by Django 6.0.4 on 2026-04-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_device_armazenamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='armazenamento',
        ),
        migrations.AddField(
            model_name='device',
            name='armazenamento_total',
            field=models.IntegerField(default=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='armazenamento_usado',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
