# Generated by Django 6.0.4 on 2026-04-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_device_armazenamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='bateria_percentual',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='device',
            name='duracao_media_bateria',
            field=models.CharField(default='Nao informado', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='memoria_ram',
            field=models.CharField(default='Nao informado', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='placa_video',
            field=models.CharField(default='Nao informado', max_length=120),
        ),
        migrations.AddField(
            model_name='device',
            name='status_descricao',
            field=models.CharField(default='No lugar certo e carregando', max_length=200),
        ),
    ]
